### ISSUE TITLE
More info menu overflows on mobile

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/connect#221]
![image](https://user-images.githubusercontent.com/8762862/174898153-72730dd8-4a81-4009-a228-3525120dbf9e.png)

**Comment by jwooning** [comment]
Note that the issue here isn't that the menu doesn't fit on a mobile screen, the size of the menu is fine.

The issue is that if the route data is still being loaded right after opening the route. First the menu renders with less text (see below), then after the data is loaded, the menu gets wider and overflows the window.

![image](https://user-images.githubusercontent.com/3130115/177301982-ae34b034-2fe4-4cc0-8af0-763539955840.png)
